all: blur gamma_grey gamma_rgb gamma_rgb_multi histo gamma_curve histo_rgb profil test_couleur test_grey test_grey_2 test_grey_3 seuil_x interpolation interpolation_curve

blur: blur.cpp
	g++ blur.cpp -o blur

gamma_grey: gamma_grey.cpp
	g++ gamma_grey.cpp -o gamma_grey

gamma_rgb: gamma_rgb.cpp
	g++ gamma_rgb.cpp -o gamma_rgb

gamma_rgb_multi: gamma_rgb_multi.cpp
	g++ gamma_rgb_multi.cpp -o gamma_rgb_multi

histo: histo.cpp
	g++ histo.cpp -o histo

gamma_curve: gamma_curve.cpp
	g++ gamma_curve.cpp -o gamma_curve

histo_rgb: histo_rgb.cpp
	g++ histo_rgb.cpp -o histo_rgb

profil: profil.cpp
	g++ profil.cpp -o profil

test_couleur: test_couleur.cpp
	g++ test_couleur.cpp -o test_couleur


test_grey: test_grey.cpp
	g++ test_grey.cpp -o test_grey

test_grey_2: test_grey_2.cpp
	g++ test_grey_2.cpp -o test_grey_2

test_grey_3: test_grey_3.cpp
	g++ test_grey_3.cpp -o test_grey_3

seuil_x: seuil_x.cpp
	g++ seuil_x.cpp -o seuil_x

interpolation: interpolation.cpp
	g++ interpolation.cpp -o interpolation

interpolation_curve: interpolation_curve.cpp
	g++ interpolation_curve.cpp -o interpolation_curve
